
/**
 * @license Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.html or http://ckeditor.com/license
 */

/**
 * This file was added automatically by CKEditor builder.
 * You may re-use it at any time at http://ckeditor.com/builder to build CKEditor again.
 * 
 * NOTE: 
 *    This file is not used by CKEditor, you may remove it.
 *    Changing this file will not change your CKEditor configuration.
 */

var CKBUILDER_CONFIG = {
	skin: 'moono',
	preset: 'full',
	ignore: [
		'dev',
		'.gitignore',
		'.gitattributes',
		'README.md',
		'.mailmap'
	],
	plugins : {
		'about' : 0,
		'a11yhelp' : 0,
		'dialogadvtab' : 0,
		'basicstyles' : 0,
		'bidi' : 0,
		'blockquote' : 0,
		'clipboard' : 0,
		'colorbutton' : 0,
		'colordialog' : 0,
		'templates' : 0,
		'contextmenu' : 0,
		'div' : 0,
		'resize' : 0,
		'toolbar' : 0,
		'elementspath' : 0,
		'enterkey' : 0,
		'entities' : 0,
		'filebrowser' : 0,
		'find' : 0,
		'flash' : 0,
		'floatingspace' : 0,
		'font' : 0,
		'forms' : 0,
		'format' : 0,
		'htmlwriter' : 0,
		'horizontalrule' : 0,
		'iframe' : 0,
		'wysiwygarea' : 0,
		'image' : 0,
		'indent' : 0,
		'smiley' : 0,
		'justify' : 0,
		'link' : 0,
		'list' : 0,
		'liststyle' : 0,
		'magicline' : 0,
		'maximize' : 0,
		'newpage' : 0,
		'pagebreak' : 0,
		'pastetext' : 0,
		'pastefromword' : 0,
		'preview' : 0,
		'print' : 0,
		'removeformat' : 0,
		'save' : 0,
		'selectall' : 0,
		'showblocks' : 0,
		'showborders' : 0,
		'sourcearea' : 0,
		'specialchar' : 0,
		'scayt' : 0,
		'stylescombo' : 0,
		'tab' : 0,
		'table' : 0,
		'tabletools' : 0,
		'undo' : 0,
		'wsc' : 0,
		'dialog' : 0,
		'dialogui' : 0,
		'panelbutton' : 0,
		'button' : 0,
		'floatpanel' : 0,
		'panel' : 0,
		'menu' : 0,
		'popup' : 0,
		'fakeobjects' : 0,
		'richcombo' : 0,
		'listblock' : 0,
		'menubutton' : 0
	},
	languages : {
		'af' : 1,
		'sq' : 1,
		'ar' : 1,
		'eu' : 1,
		'bn' : 1,
		'bs' : 1,
		'bg' : 1,
		'ca' : 1,
		'zh-cn' : 1,
		'zh' : 1,
		'hr' : 1,
		'cs' : 1,
		'da' : 1,
		'nl' : 1,
		'en' : 1,
		'en-au' : 1,
		'en-ca' : 1,
		'en-gb' : 1,
		'eo' : 1,
		'et' : 1,
		'fo' : 1,
		'fi' : 1,
		'fr' : 1,
		'fr-ca' : 1,
		'gl' : 1,
		'ka' : 1,
		'de' : 1,
		'el' : 1,
		'gu' : 1,
		'he' : 1,
		'hi' : 1,
		'hu' : 1,
		'is' : 1,
		'it' : 1,
		'ja' : 1,
		'km' : 1,
		'ko' : 1,
		'ku' : 1,
		'lv' : 1,
		'lt' : 1,
		'mk' : 1,
		'ms' : 1,
		'mn' : 1,
		'no' : 1,
		'nb' : 1,
		'fa' : 1,
		'pl' : 1,
		'pt-br' : 1,
		'pt' : 1,
		'ro' : 1,
		'ru' : 1,
		'sr' : 1,
		'sr-latn' : 1,
		'sk' : 1,
		'sl' : 1,
		'es' : 1,
		'sv' : 1,
		'th' : 1,
		'tr' : 1,
		'ug' : 1,
		'uk' : 1,
		'vi' : 1,
		'cy' : 1,
	}
};